### ISSUE TITLE
Guzzle version

### ISSUE THREAD

**Issue by JesseWynants** [delighted/delighted-php#1]
Hi Guys,

I'm having some issues installing this through composer. You guys require  "guzzlehttp/guzzle": "3.8.1", but we're using "guzzlehttp/guzzle": "4.*". Would this break your lib if you would made it "guzzlehttp/guzzle": ">= 3.8.1"?

Cheers,

Jesse

**Comment by mkdynamic** [comment]
@JesseWynants Sorry to hear that caused a conflict. I think we could relax the version specifier for that, as you suggested. I'll run some tests to verify nothing breaks.

**Comment by mkdynamic** [comment]
Ok, I ran some tests and it looks like the API changed a bunch in 4.x, and also dropped support for PHP < 5.4. So it looks like we'll need to add a shim to continue support for both 3.x and 4.x (and possibly 5.x). Since this is such a common HTTP library, it seems worthwhile because I imagine conflicts like this will be common.

Will start work on a shim.

**Comment by JesseWynants** [comment]
Any idea on timeframe? Don't want to push you, just want to decide if I'm going to wait or find another way(curl) :-)

**Comment by mkdynamic** [comment]
Hi @JesseWynants, no worries. We're going to need to write an adapter that will support Guzzle 3, 4 and 5 for broad compatibility. I don't have an solid ETA, but I think it'll be a few days at least before we have something.

**Comment by digitalbase** [comment]
@mkdynamic any way you could relax the guzzle requirement to ~3.9? That would fix the conflict with https://github.com/intercom/intercom-php

**Comment by mkdynamic** [comment]
@digitalbase Yes, that should safe. Verifying currently that doesn't break anything...

**Comment by mkdynamic** [comment]
@digitalbase Done. Just pushed `v1.0.0-beta.2` with a dependency of `~3.8`, so that should allow 3.9. Let me know how that goes.

**Comment by mkdynamic** [comment]
Fixed in https://github.com/delighted/delighted-php/issues/2.
