### ISSUE TITLE
Prevent sending survey email when user gets created

### ISSUE THREAD

**Issue by hvlucas** [delighted/delighted-php#12]
After setting 'send' flag to false when creating a user like so:
`Person::create(['email' => 'email@email.com', 'name' => 'Testing Delighted', 'send' => false]);`  
It still sends the initial survey email (I used a 10 minute email and a dummy hotmail account I have to test it out). It is working intently when resubscribing a person who was unsubscribed (doesn't send the email like I want)
'Person' is what I named the 'Delighted\Person' class.
I'm using version v1.1.0, do newer version have this issue patched?  
Thank you

**Comment by mkdynamic** [comment]
@hvlucas Apologies for this bug. We're working on a fix (there is a failing test case at https://github.com/delighted/delighted-php/pull/11).

In the meantime, as a workaround, if you pass `false` as a string, i.e. `Person::create(['email' => 'email@email.com', 'name' => 'Testing Delighted', 'send' => 'false']);` that should work. Let me know how that goes.

**Comment by hvlucas** [comment]
Thank you for the response, that worked fine!  
I'm not sure if any of you are responsible for the API documentation page in the Delighted website but they are missing 'Listing Active people' from the sidebar!  
https://delighted.com/docs/api/listing-active-people

**Comment by mkdynamic** [comment]
Good catch, thanks @hvlucas

**Comment by rayrutjes** [comment]
@mkdynamic the documentation sidebar still does not show the link to the listing of users endpoint.
I'm fortunate to have found this issue.

**Comment by rayrutjes** [comment]
BTW the API client should really try to enforce the casting to string for the `send` parameter.
Given the documentation clearly states it expects a boolean:
![image](https://user-images.githubusercontent.com/5570853/53802436-1db05e80-3f42-11e9-872f-34e71b4f45cf.png)

**Comment by mkdynamic** [comment]
@rayrutjes Yes, sorry about this. Please keep an eye on for https://github.com/delighted/delighted-php/pull/11 for a fix soon.
