### ISSUE TITLE
Creating survey subscription & unsubscribing users

### ISSUE THREAD

**Issue by hvlucas** [delighted/delighted-php#13]
Hello again delighted team!

I noticed this issue when trying to resubscribe someone through the API. When I unsubscribe somebody using:  
`Unsubscribe::create(['person_email' => $client->email]);`  
It unsubscribes correctly and puts the user with that email on that list in delighted.com.
Now when I resubscribe them using their same email:  
`Person::create(['email' => $client->email, 'name' => $client->full_name(), 'delay' => 7884000]);`  
They stay in that unsubscribed list but the 'next_survey_scheduled_at' is updated to the delay I set. Would they receive a survey email when the next survey is scheduled and they are in the Unsubscribed list?
I'm not sure if I have to delete them from delighted first using `Client::delete` method, then resubscribe them but let me know what the best approach is!  
Thank you,
Lucas

**Comment by mkdynamic** [comment]
Hi @hvlucas! Once somebody has been unsubscribed, they will remain unsubscribed unless you explicitly re-subscribe them (which currently you cannot do via the API, only via the UI on the People page).

To clarify, if you call `Person::create` for an email that you previously unsubscribed, they will not be sent a survey (even though the response suggests they might, if you went solely on `next_survey_scheduled_at`). We perform unsubscribe checks at the last minute to ensure we never email folks that have unsubscribed.

**Comment by hvlucas** [comment]
Oh alright, thank you for the clarification. 
Do you know when it's going to be on the works to be added to the API? For now I'll just set an alert to do it manually when clients need to be re-added

**Comment by hvlucas** [comment]
I tried doing it manually by adding a person again through the Autopilot and they still stay in the Unsubscribed list.  
These people I unsubscribed them through the API

**Comment by mkdynamic** [comment]
>I tried doing it manually by adding a person again through the Autopilot and they still stay in the Unsubscribed list.

@hvlucas Ah, sorry, my bad! I was completely wrong about being able to re-subscribe via the UI. Currently we only support re-subscribing via customer support. We take a very cautious approach with this because we want to be extremely respectful for when folks unsubscribe. If you email hello@delighted.com our customer support can help handle any individual re-subscribe requests.

**Comment by hvlucas** [comment]
@mkdynamic Wouldn't it make sense to have clients be able to be re-subscribed if they were unsubscribed throught the API. Meaning, it wasn't physically themselves who did it. Once the owner of the email does unsub then the API wouldn't be able to resub. Just my 2cents!  
I'll close this issue, thank you so much for helping me out with my questions :+1:

**Comment by mkdynamic** [comment]
>Wouldn't it make sense to have clients be able to be re-subscribed if they were unsubscribed throught the API. Meaning, it wasn't physically themselves who did it. Once the owner of the email does unsub then the API wouldn't be able to resub.

Thanks, that's a good idea. I'll capture this suggestion on the ticket we have for adding re-subscribe functionality to the API (it's certainly under consideration, but cannot make any promises about timeframe -- your suggestion could help).
