### ISSUE TITLE
Arquitectural problem on class Person

### ISSUE THREAD

**Issue by mariano-gomez** [delighted/delighted-php#14]
Hi! I'm working with your API, and we're having problem for some specific cases (which ones, we can't know because we can't debug the code properly) when we try to create new users.
Right now, all we can do is to wrap the Person::create() call in a try/catch block, the thing is that this doesn't show us the API response data that would help us (as the docs reads, the "Information about the specific errors will be returned in the response" for a 422 response).
Unfortunately, since this code is part of a vendor folder, and therefore it's not being tracked by git (alas, we can't modify it), i think it would be great if you get another approach to this, for example:

$response = Client::post('people', $props);
try {
        return new Person($response);
}  catch (Exception $e) {
        return $response;
}

And then, if the person couldn't be created, at least we can see the api response to know what went wrong.

See ya!

**Comment by kindjar** [comment]
The exception class raised by the library should be a `RequestException` and it has a `getData` method that returns the body of the API response.
