### ISSUE TITLE
Guzzle deprecated

### ISSUE THREAD

**Issue by Jarlskov** [delighted/delighted-php#7]
The library depends on guzzle/guzzle which is no longer maintained https://packagist.org/packages/guzzle/guzzle and change that it'll be upgraded to the still maintained guzzlehttp/guzzle ?

**Comment by akalongman** [comment]
@Jarlskov you should see this PR https://github.com/delighted/delighted-php/pull/10

**Comment by Jarlskov** [comment]
That would be awesome!

**Comment by mkdynamic** [comment]
This was addressed in #10 (now merged), thanks to @akalongman.

@Jarlskov If you want to try the `2.0.0-beta` and let us know if that works for you, your feedback would be much appreciated:
https://packagist.org/packages/delighted/delighted#v2.0.0-beta
